### ISSUE TITLE
Nutze von GC.Collect beschränken

### ISSUE THREAD

**Issue by lousystems** [Sqrroot02/Kalender#2]
**Vermeiden vom aufruf des GC**
Im generellen gilt, dass man versuchen sollte den Aufruf des GC zu vermeiden oder zu beschränken. Es giebt einige ausnahmen. 
In [CalendarData.cs](https://github.com/Sqrroot02/Kalender/blob/master/Kalender/Data/CalendarData.cs) wird der GC zweimal hintereinander gecallt. Hier wird es dann unnötige Performance Einbußen geben.

**Comment by Sqrroot02** [comment]
Vielen Dank. Der doppelte GC.Collect Aufruf wurde entfernt!
